language: go

go:
  - "1.13.x"
  - tip

install:
  - travis_retry go get -u golang.org/x/tools/cmd/cover
  - travis_retry go get -u github.com/mattn/goveralls

script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - goveralls -service=travis-ci -coverprofile=coverage.out
